# Generated by Django 2.2.12 on 2021-02-09 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutaions_commits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutationcommit',
            name='error',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='mutationcommit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
