# Generated by Django 2.2.12 on 2021-02-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutaions_commits', '0002_auto_20210209_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationcommit',
            name='error',
            field=models.TextField(default=None, null=True),
        ),
    ]
