# Generated by Django 2.2.12 on 2021-02-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutaions_commits', '0004_auto_20210209_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutationCommit',
        ),
    ]
