# Generated by Django 2.2.12 on 2021-02-16 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutaions_commits', '0006_mutationcommit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationcommit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
